version: "2"

services:

  app:
    image: prometheus-alerting-app:1.0.0
    ports:
      - "8000:8000"
    container_name: app

  prometheus:
    image: "prom/prometheus:v2.44.0"
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./prometheus:/etc/prometheus
      - ./data/prometheus:/prometheus
    container_name: prometheus

  grafana:
    image: "grafana/grafana:10.0.0"
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
    container_name: grafana

  alert-manager:
    image: "prom/alertmanager:main"
    ports:
      - "9093:9093"
    container_name: alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager
      - ./data/alertmanager:/alertmanager

volumes:
  prometheus-data: