version: "2"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    container_name: app
  prometheus:
    image: "prom/prometheus:v2.44.0"
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./prometheus:/etc/prometheus
      - ./prometheus-data:/prometheus
    container_name: prometheus
  grafana:
    image: "grafana/grafana:10.0.0"
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
    container_name: grafana

volumes:
  prometheus-data: