global:
  # How frequently to scrape targets by default.
  scrape_interval: 5s

  # How frequently to evaluate rules.
  evaluation_interval: 15s

# A list of scrape configurations.
scrape_configs:
  - job_name: 'python-app'
    static_configs:
      - targets: ['app:8000']

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

rule_files:
  - "prometheus-rules.yml"